//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHomeFurniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANHSANPHAM
    {
        public int MaAnh { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string DuongDan { get; set; }
        public Nullable<bool> LaAnhChinh { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
