//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHomeFurniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int MaDG { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> SoSao { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
