//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHomeFurniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.ANHSANPHAMs = new HashSet<ANHSANPHAM>();
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.SANPHAM_YEUTHICH = new HashSet<SANPHAM_YEUTHICH>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string Slug { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public string ChatLieu { get; set; }
        public string KichThuoc { get; set; }
        public string MauSac { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<int> MaTH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANHSANPHAM> ANHSANPHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM_YEUTHICH> SANPHAM_YEUTHICH { get; set; }
    }
}
