//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHomeFurniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM_YEUTHICH
    {
        public int MaKH { get; set; }
        public int MaSP { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
