//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHomeFurniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int MaTin { get; set; }
        public string TieuDe { get; set; }
        public string Slug { get; set; }
        public string TomTat { get; set; }
        public string NoiDung { get; set; }
        public string AnhTin { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> MaAd { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
    }
}
